# Generated by Django 3.1.3 on 2020-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('BG', 'Badge'), ('PR', 'Poster'), ('KC', 'Keychain'), ('PN', 'Pen'), ('LK', 'Locket')], max_length=2)),
                ('description', models.TextField()),
                ('qty', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/%Y/%m/%d')),
            ],
            options={
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
